# docker-compose.yml
version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: edi-postgres
    environment:
      POSTGRES_DB: edi_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - edi-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: edi-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@edi.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - edi-network
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  edi-network:
    driver: bridge
